Sprint 2/step 1
rays1410/react-burger pull request #4
Opened 2023-01-19 00:46 UTC by rays1410

Добавил контекст, добавил запрос для номера заказа, сделал useToggle для модалки, сделал useOrder для заказа, добавил мемоизацию ингредиентов. Пофиксил скролл (раньше немного не доезжал до нужного <div>. TODO: добавить <Loader/> для ингрединтов и для заказа в модалке)

2023-01-19 04:42 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется контекст;

### **Но есть несколько замечаний, которые рекомендую исправить:**

- Активной в хедере должна быть только первая ссылка - https://disk.yandex.com/i/6Vp3s2KMOwJz6A;

- В запросе `/orders` нужно чтобы id у булок (булки одинаковые) были в начале и в конце массива: https://disk.yandex.com/i/BwV2s_8Kq8JioQ;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-01-19 04:42 UTC, ArslanDev666 commented on src/components/app/app.tsx
> +    getData(dataState, setDataState, INGREDIENTS_URL);
**Рекомендую исправить:**

Не стоит передавать коллбэки в функцию запроса, лучше выполнять их после получения данных.

```js
  useEffect(() => {
    getIngredients()
      .then(setIngredients)
      .catch(() => alert("Во время загрузки ингредиентов произошла ошибка."))
      .finally(() => setIngredientsLoading(false));
  }, []);
```

2023-01-19 04:42 UTC, ArslanDev666 commented on src/services/appContext.tsx
> +};
**Можно лучше:**

Немного не понимаю смысла данной обёртки, почему бы просто сразу не сделать провайдер в app компоненте?

2023-01-19 04:42 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
> +  const { dataState } = useContext(DataContext) as DataContextType;
**Можно лучше:**

вроде бы у useContext есть дженерик

2023-01-19 21:51 UTC, rays1410 commented on src/services/appContext.tsx
> +export const DataContext = createContext<DataContextType>({} as DataContextType);
Я по поводу `{} as DataContextType` не уверен. Выглядит не очень, но я пока не разобрался как по другому сделать.

2023-01-19 21:53 UTC, rays1410 commented on src/components/app/app.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
на 19 строчку ругается eslint.

2023-01-20 04:55 UTC, ArslanDev666 commented on src/services/appContext.tsx
> +export const DataContext = createContext<DataContextType>({} as DataContextType);
```js
export const DataContext = createContext<DataContextType | null>(null);
```

Вот так лучше вроде выглядит)) 
Также, если нет значений, то лучше использовать null, а не пустой объект)

2023-01-20 04:59 UTC, ArslanDev666 commented on src/services/appContext.tsx
> +export const DataContext = createContext<DataContextType>({} as DataContextType);
https://felixgerschau.com/react-typescript-context/ - вот есть неплохая статейка на тему контекста with ts.

2023-01-20 04:59 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены;

### **Но есть 1 замечание, которое рекомендую исправить:**

- Активной в хедере должна быть только первая ссылка, а эти иконки должны быть одного цвета с текстом https://disk.yandex.com/i/bCsiqww9dJBa0Q;
  Также, иконка тоже должна быть обёрнута в ссылку, а не только текст.

2023-01-20 20:25 UTC, rays1410 commented on src/services/appContext.tsx
> +export const DataContext = createContext<DataContextType>({} as DataContextType);
Спасибо!

2023-01-21 11:40 UTC, merged