Sprint 3/step 1
rays1410/react-burger pull request #6
Opened 2023-02-18 18:18 UTC by rays1410

2023-02-19 06:28 UTC, andryxxa93 requested changes
Здравствуйте! У вас очень хороший проект!
Что понравилось:
- В `ProtectedRoute` есть защита роутов для авторизованных и не авторизованных пользователей
- Пути роутов и сообщения ошибок записаны в константы - это супер!
- Хороший `codestyle`

Что необходимо исправить:
- При нажатии на кнопку «Оформить заказ» неавторизованный пользователь должен переадресовываться на маршрут `/login`. Только авторизованные пользователи могут делать заказы.
- При открытии ингредиента по прямой ссылке показывается 404 страница. И почему-то к роуту в конце добавляется `/*`.

https://user-images.githubusercontent.com/60173362/219932201-d7c06473-f71e-4232-988e-ae3cb36aa488.mov

- Роут `/reset-password` должен быть доступен только через `/forgot-password`
- Все данные форм необходимо отправлять по событию `onSubmit`
- Если попытаться изменить данные юзера в форме с протухшим токеном, то токен обновляется и данные отправляются, но не измененные. 

https://user-images.githubusercontent.com/60173362/219932741-e5036c0f-c022-4fd0-a041-4a3b0a4fe1e2.mov

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-19 06:28 UTC, andryxxa93 commented on src/components/app/app.tsx
> +  // const dataStatus = useSelector((state: any) => state.ingredients.status);
**Можно улучшить**
Ненужный код лучше удалять

2023-02-19 06:28 UTC, andryxxa93 commented on .vscode/launch.json
> +    "version": "0.2.0",
**Можно лучше**
Такие файлы не нужный в github потому что кто-то может пользоваться другими IDE.

2023-02-19 06:28 UTC, andryxxa93 commented on src/components/protected-route/protected-route.tsx
> +  const { isAuthChecked, isUserData } = useAppSelector(
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-02-19 19:27 UTC, rays1410 commented on src/components/burger-constructor/burger-constructor.tsx
> +    }
кейс с неавторизованным пользователем

2023-02-19 19:28 UTC, rays1410 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  const { ingredientsData } = useAppSelector(getIngredientsSlice);
заменил функции в `useAppSelector`

2023-02-19 19:29 UTC, rays1410 commented on src/components/ingredient-details/ingredient-details.tsx
> +    <Loader />
Добавил некрасивый лоудер, потом его допилю

2023-02-19 19:29 UTC, rays1410 commented on src/pages/login-page/login-page.tsx
> +      <form onSubmit={(e) => handleLogin(e)} className={loginStyles.upperBlock}>
Формы

2023-02-19 19:31 UTC, rays1410 commented on src/pages/profile-page/profile-page.tsx
> +      });
Если я изменяю дату и у меня нет аксес токена, то я иду за новым и потом снова изменяю данные. А если обнаружится что у меня и рефреш токена нет, то я очищаю юзера и перекидываю его на логин

2023-02-19 19:31 UTC, rays1410 commented on src/utils/utils.ts
> +  state.resetPasswordSlice;
функции для `useSelector`

2023-02-20 06:33 UTC, andryxxa93 requested changes
Супер, вы отлично поработали. Работа принята, удачного продолжения обучения!
**Можно лучше**
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return `<Redirect to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Redirect`)

2023-02-25 18:22 UTC, merged